CREATE TABLE IF NOT EXISTS departments (
    id BIGINT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS files (
    id BIGINT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    employee_number VARCHAR(100) NOT NULL,
    department_id BIGINT NOT NULL,
    position VARCHAR(100) NOT NULL,
    hire_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    profile_image_id BIGINT,

    check ( status IN('ACTIVE', 'ON_LEAVE', 'RESIGNED') ),

    FOREIGN KEY (department_id)
        REFERENCES departments(id)
        ON DELETE NO ACTION,

    FOREIGN KEY (profile_image_id)
        REFERENCES files(id)
        ON DELETE SET NULL

);